apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: architecture-gallery
  namespace: bluefalconink
  labels:
    cloud.googleapis.com/location: us-central1
    app: architecture-gallery
    org: bluefalconink-llc
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      serviceAccountName: architect-ai-foreman@bluefalconink-prod.iam.gserviceaccount.com
      containers:
        - image: us-central1-docker.pkg.dev/bluefalconink/bluefalconink-apps/architecture-gallery:latest
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          env:
            - name: GITHUB_ORG
              value: "koreric75"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-pat
                  key: token
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
